---
- hosts: localhost
  tasks:

    - name: "Add PHP repository"
      apt_repository:
        repo: "ppa:ondrej/php"
        update_cache: yes

    - name: "Add package"
      package:
        name: "{{ item }}"
      loop:
        - "php7.2-cli"
        - "php7.2-amqp"
        - "php7.2-apcu"
        - "php7.2-bcmath"
        - "php7.2-bz2"
        - "php7.2-calendar"
        - "php7.2-cgi"
        - "php7.2-common"
        - "php7.2-ctype"
        - "php7.2-curl"
        - "php7.2-dba"
        - "php7.2-dev"
        - "php7.2-dom"
        - "php7.2-ds"
        - "php7.2-enchant"
        - "php7.2-exif"
        - "php7.2-fpm"
        - "php7.2-ftp"
        - "php7.2-gd"
        - "php7.2-gettext"
        - "php7.2-gmp"
        - "php7.2-iconv"
        - "php7.2-imagick"
        - "php7.2-imap"
        - "php7.2-intl"
        - "php7.2-json"
        - "php7.2-ldap"
        - "php7.2-mbstring"
        - "php7.2-memcached"
        - "php7.2-mongodb"
        - "php7.2-msgpack"
        - "php7.2-mysqli"
        - "php7.2-mysqlnd"
        - "php7.2-odbc"
        - "php7.2-opcache"
        - "php7.2-pdo"
        - "php7.2-pgsql"
        - "php7.2-phar"
        - "php7.2-phpdbg"
        - "php7.2-posix"
        - "php7.2-pspell"
        - "php7.2-psr"
        - "php7.2-redis"
        - "php7.2-shmop"
        - "php7.2-snmp"
        - "php7.2-soap"
        - "php7.2-sockets"
        - "php7.2-sqlite3"
        - "php7.2-sysvmsg"
        - "php7.2-sysvsem"
        - "php7.2-sysvshm"
        - "php7.2-tidy"
        - "php7.2-xdebug"
        - "php7.2-xml"
        - "php7.2-xmlreader"
        - "php7.2-xmlrpc"
        - "php7.2-xsl"
        - "php7.2-zip"

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Clear cache
      command: apt-get clean all

    - name: Install composer
      get_url:
        url: https://getcomposer.org/composer.phar
        dest: /usr/local/bin/composer
        mode: "0755"

    - name: "Update composer"
      command: "composer self-update --stable"

    - name: "Install composer plugin prestissimo"
      command: "composer global require hirak/prestissimo"
