---
- hosts: localhost
  tasks:

    - name: "Add Apache repository"
      apt_repository:
        repo: "ppa:ondrej/apache2"
        update_cache: yes

    - name: "Add package"
      package:
        name: "{{ item }}"
      loop:
        - "apache2"
        - "php7.4-fpm"
        - "libapache2-mod-php7.4"

    - name: "Enable Apache module"
      command: "a2enmod {{ item }}"
      loop:
        - "rewrite"
        - "headers"
        - "deflate"
        - "http2"
        - "actions"
        - "php7.4"

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Clear cache
      command: apt-get clean all
