---
- hosts: localhost
  tasks:
    - name: Install OpenSSL deps
      pip:
        name: pyOpenSSL
        state: present

    - name: "Add Apache repository"
      apt_repository:
        repo: "ppa:ondrej/apache2"
        update_cache: yes

    - name: "Add package"
      package:
        name: "{{ item }}"
      loop:
        - "apache2"
        - "php7.3-fpm"
        - "libapache2-mod-php7.3"

    - name: "Enable Apache module"
      command: "a2enmod {{ item }}"
      loop:
        - "rewrite"
        - "headers"
        - "deflate"
        - "http2"
        - "actions"
        - "php7.3"
        - "ssl"

    - name: Enable Apache default sites
      command: "a2ensite 000-default default-ssl"

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: Clear cache
      command: apt-get clean all
